---

# We don't want to interrupt running jobs in order to prevent corruption
- name: Query For Running Jobs Completion
  # Can not use map filter due to special character '@'
  # Forced to use jinja2 loop
  # Jobs that are being executed will not be able to be deleted, we will attempt to wait
  # for them to finish
  # Also not all iDRAC versions support Deleting Job Queue via Redfish
  vars:
    idrac_jobs_uris: >-
      {%- set jobs=[] -%}
      {%- for job in idrac_runnig_jobs -%}
        {{ jobs.append(idrac_uri_protocol + '://' + inventory_hostname + job['json']['@odata.id']) }}
      {%- endfor -%}
      {{ jobs }}
  ansible.builtin.uri:
    url: "{{ item }}"
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    force_basic_auth: True
    return_content: True
    validate_certs: "{{ validate_ssl_certs }}"
  register: idrac_runnig_jobs_query
  retries: "{{ task_retries }}"
  delay: 5
  until: idrac_runnig_jobs_query['json']['JobState'] == 'Completed'
  loop: "{{ idrac_jobs_uris }}"
  when: idrac_runnig_jobs
