---

- name: Set Facts
  set_fact:
    idrac_scheduled_bios_jobs: {}
    idrac_runnig_jobs: {}

- name: Retrieve Jobs From iDRAC
  include_role:
    name: idrac_configuration
    tasks_from: retrieve_idrac_jobs
  when: not ansible_check_mode

- name: Check If There Are Non Completed Jobs
  block:
    - name: Check For Scheduled BIOS Configuration Jobs
      set_fact:
        idrac_scheduled_bios_jobs: "{{ idrac_job['results'] | selectattr('content', 'contains', 'Task successfully scheduled') | selectattr('content', 'contains', 'BIOSConfiguration') | list }}"
      when: idrac_job['results'] | selectattr('content', 'contains', 'Task successfully scheduled') | selectattr('content', 'contains', 'BIOSConfiguration') | list

    - name: Check For Running Jobs
      set_fact:
        idrac_runnig_jobs: "{{ idrac_job['results'] | selectattr('content', 'contains', 'Job in progress') | list }}"
      when: idrac_job['results'] | selectattr('content', 'contains', 'Job in progress') | list
  when: idrac_job['results']

- name: Deleting Scheduled BIOS Configuration Jobs If Present
  # Can not use map filter due to special character '@'
  # Forced to use jinja2 loop
  # Jobs that are being executed will not be able to be deleted, we will attempt to wait
  # for them to finish
  # Not all iDRAC versions support Deleting Job Queue via Redfish
  vars:
    idrac_jobs_uris: >-
      {%- set jobs=[] -%}
      {%- for job in idrac_scheduled_bios_jobs -%}
        {{ jobs.append(idrac_uri_protocol + '://' + inventory_hostname + job['json']['@odata.id']) }}
      {%- endfor -%}
      {{ jobs }}
  ansible.builtin.uri:
    url: "{{ item }}"
    method: 'DELETE'
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    force_basic_auth: True
    return_content: True
    validate_certs: "{{ validate_ssl_certs }}"
  register: idrac_scheduled_job_deletion
  retries: "{{ task_retries }}"
  delay: 5
  until: >-
    (idrac_scheduled_job_deletion['status'] == 200) or
    (idrac_scheduled_job_deletion['status'] == 400 and idrac_scheduled_job_deletion['json']['error']['@Message.ExtendedInfo'] | selectattr('Message', 'contains', 'Invalid Job ID') | list)
  loop: "{{ idrac_jobs_uris }}"
  when:
    - idrac_scheduled_bios_jobs is defined
    - not check_bios_jobs

- name: Wait For Running Jobs To Complete
  include_role:
    name: idrac_configuration
    tasks_from: wait_for_running_jobs
