---

- name: Ensure Jobs Are Completed Before Any Restart Action
  block:
    - name: Set Facts
      set_fact:
        idrac_runnig_jobs: {}

    - name: Retrieve Jobs From iDRAC
      include_role:
        name: idrac_configuration
        tasks_from: retrieve_idrac_jobs
      when: not ansible_check_mode

    - name: Wait For Running Jobs To Complete
      include_role:
        name: idrac_configuration
        tasks_from: wait_for_running_jobs
  when:
    - power_action in ['PowerForceRestart', 'PowerGracefulRestart', 'PowerReboot']
    - not ansible_check_mode

- name: Execute Power Action '{{ power_action }}' On iDRAC
  community.general.remote_management.redfish.redfish_command:
    category: Systems
    command: "{{ power_action }}"
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    timeout: "{{ idrac_timeout }}"
  register: power_action_result
  retries: "{{ task_retries }}"
  until:
    - "'EOF occurred in violation of protocol' not in power_action_result['msg']"
