---

# TODO(vkhitrin): Consider exposing more information and/or let the user customize collected info
- name: Get Generic iDRAC Info (This May Take Time)
  community.general.remote_management.redfish.redfish_info:
    category: Systems
    command: all
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    timeout: "{{ idrac_timeout }}"
  register: generic_redfish_info

- name: Get Manager iDRAC Info
  community.general.remote_management.redfish.idrac_redfish_info:
    category: Manager
    command: GetManagerAttributes
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    timeout: "{{ idrac_timeout }}"
  register: manager_redfish_info

- name: Print Collected iDRAC Info
  debug:
    msg: "{{ generic_redfish_info | combine(manager_redfish_info) }}"
