- name: Check if can authenticate with iDRAC
  ansible.builtin.uri:
    url: "{{ idrac_uri }}"
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    force_basic_auth: True
    return_content: True
    validate_certs: "{{ validate_certs }}"
