---

- name: TEST BOOT ORDER
  debug:
    msg: "{{ host_boot_order }}"

- name: TEST COMBINED BIOS CONFIGURATION
  debug:
    msg: "{{host_bios_configuration}}"

- name: Apply BIOS Configuration
  community.general.redfish_config:
    category: Systems
    command: SetBiosAttributes
    bios_attributes: "{{ host_bios_configuration | default(omit) }}"
    baseuri: "{{ inventory_hostname }}"
    boot_order: "{{ host_boot_order | default(omit) }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  register: bios_attribute_change

- debug: var=bios_attribute_change

- name: Create BIOS Configuration Job (Schedule BIOS Setting Update) If Needed
  community.general.idrac_redfish_command:
    category: Systems
    command: CreateBiosConfigJob
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  register: bios_config_job
  when: bios_attribute_change is changed

- name: Power Off iDRAC Before Applying New BIOS Settings If Needed
  community.general.redfish_command:
    category: Systems
    command: PowerGracefulShutdown
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  register: bios_idrac_poweroff
  when: bios_attribute_change is changed

- name: Power On iDRAC To Apply New BIOS Settings If Needed
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
  register: bios_idrac_reboot
  retries: "{{ task_retries }}"
  until: "'URL' not in bios_idrac_reboot['msg']"
  when: bios_config_job is changed
